version: "3.8"

services:
  asf-bot-telegram:
    build:
      context: ./
      dockerfile: ASF-Bot.Telegram/Dockerfile
      args:
        DOTNET_VERSION: 8.0
    image: asf-bot-telegram:latest
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes: []
