name: docker-publish-latest

on:
  release:
    types: [released]

env:
  PLATFORMS: linux/amd64,linux/arm64
  TAG: latest

permissions:
  contents: read
  packages: write

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6.0.1
      with:
        show-progress: false
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.11.1

    - name: Login to ghcr.io
      uses: docker/login-action@v3.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Prepare environment outputs
      shell: sh
      run: |
        set -eu

        echo "FIXED_TAG=$(echo ${{ github.ref }} | cut -d '/' -f 3)" >> "$GITHUB_ENV"
        echo "DATE_ISO8601=$(date --iso-8601=seconds --utc)" >> "$GITHUB_ENV"
        echo "GHCR_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
        echo "DH_REPOSITORY=$(echo ${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

    - name: Build and publish Docker image from Dockerfile
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: Dockerfile
        platforms: ${{ env.PLATFORMS }}
        provenance: true
        sbom: true
        labels: |
          org.opencontainers.image.created=${{ env.DATE_ISO8601 }}
          org.opencontainers.image.version=${{ env.FIXED_TAG }}
          org.opencontainers.image.revision=${{ github.sha }}
        tags: |
          ghcr.io/${{ env.GHCR_REPOSITORY }}:${{ env.TAG }}
          ${{ env.DH_REPOSITORY }}:${{ env.TAG }}
        push: true
